import { Assistant } from "next/font/google";
import "./globals.css";
import { NavigateBefore } from "@mui/icons-material";
import Navbar from "@/utils/components/navbar/navbar";

const assistant = Assistant({ subsets: ["hebrew"] });

export const metadata = {
  title: "Test Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={assistant.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
